# Local schema
BASE_URL=http://localhost:4000
SWAGGER_ENDPOINT=${BASE_URL}/swagger.json
TYPES_OUTPUT=./frontend/src/api/schema.d.ts
TYPES_FOLDER=$(dirname $TYPES_OUTPUT)

# Ensure the output directory exists
mkdir -p $TYPES_FOLDER

# Remote schema
npx openapi-typescript $SWAGGER_ENDPOINT -o $TYPES_OUTPUT
# 🚀 https://myapi.dev/api/v1/openapi.yaml -> ./path/to/my/schema.d.ts [250ms]

# Generate API client
cat <<EOL > ./frontend/src/api/client.ts
import createClient from "openapi-fetch";
import type { paths } from "./schema.d.ts"; // generated by openapi-typescript

export const client = createClient<paths>({ baseUrl: process.env.BACKEND_URL  });
EOL

# Instructions for the user
echo "API client generated at $TYPES_OUTPUT"
echo "Please install openapi-fetch and import the generated types in your frontend code to use the API client."