import createClient from "openapi-fetch";
import type { paths } from "./schema.d.ts"; // generated by openapi-typescript

export const client = createClient<paths>({ baseUrl:import.meta.env.VITE_API_URL });
