name: FrontendCI

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  deploy:
    name: Deploy Frontend to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Build frontend
        run: npm run build:frontend
        working-directory: frontend

      - name: Handle SPA routing
        run: cp frontend/dist/404.html frontend/dist/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist